version: "3.7"

services:
  
  db:
    image: mysql:5.7.8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=petclinic
    volumes:
      - "~/docker-mysql:/var/lib/mysql/"
  app:
    build: . 
    volumes: 
      - ./src:/opt/app
    ports: 
      - 8080:8080
    environment: 
      - spring.profiles.active=mysql
      - spring.datasource.url=jdbc:mysql://db:3306/petclinic
